import { get, put, remove, uid } from './db.js';
import { initialSchedule, defaultSettings } from './seed.js';
import { isoDay, blocksForDay, clock, dateLabel, suggestPlan, mins } from './planner.js';
import { exportBackup, downloadBackup, restoreBackup } from './backup.js';

const app = document.querySelector('#app');
const types = ['subjects','tasks','schedule','exams','sessions','records'];
const state = { page: 'today', more: 'history', subjects: [], tasks: [], schedule: [], exams: [], sessions: [], records: [], settings: null, modal: null, toast: '', timerTick: null };
const days = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const esc = value => String(value ?? '').replace(/[&<>'"]/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[x]));
const today = () => isoDay();
const time = () => new Date().toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });
const subject = id => state.subjects.find(s => s.id === id)?.name || 'General';
const taskFor = id => state.tasks.find(t => t.id === id);
const formatMinutes = n => n ? `${Math.round(n)}m` : '0m';

async function init() {
  state.settings = await get('settings');
  if (!state.settings) {
    state.settings = defaultSettings(); await put('settings', state.settings);
    state.schedule = initialSchedule();
    const names = [...new Set(state.schedule.map(x => x.subject).filter(x => x !== 'ساعة في السنتر'))];
    state.subjects = names.map(name => ({ id: uid('subject'), name, color: '#61d8c2', createdAt: Date.now() }));
    await saveCollection('schedule'); await saveCollection('subjects');
  }
  for (const type of types) state[type] = (await get(type)) || state[type] || [];
  document.documentElement.dataset.theme = state.settings.theme || 'dark';
  navigator.serviceWorker?.register('./sw.js').catch(() => {});
  render();
}
async function saveCollection(name) { await put(name, state[name]); }
async function saveSettings() { await put('settings', state.settings); }
async function persistTask(task) { const i = state.tasks.findIndex(x => x.id === task.id); if (i < 0) state.tasks.unshift(task); else state.tasks[i] = task; await saveCollection('tasks'); }
function toast(message) { state.toast = message; render(); setTimeout(() => { if (state.toast === message) { state.toast = ''; render(); } }, 3200); }
function activeTimer() { return state.settings.timer || null; }
function actualMinutes(task) { return state.sessions.filter(s => s.taskId === task.id).reduce((sum, s) => sum + s.duration, 0); }
function daySessions(date) { return state.sessions.filter(s => s.date === date).reduce((s,x) => s + x.duration, 0); }
function plannedToday() { return state.tasks.filter(t => t.plannedDate === today() && t.status !== 'COMPILED').sort((a,b) => (a.plannedStart ?? 9999) - (b.plannedStart ?? 9999)); }
function completedToday() { return state.tasks.filter(t => t.completedAt && isoDay(new Date(t.completedAt)) === today()); }
function isOverdue(t) { return t.status !== 'COMPILED' && t.dueDate && t.dueDate < today(); }
function capacity() { const blocks = blocksForDay(state.schedule, today()); const fixed = blocks.reduce((s,b) => s + (b.end-b.start), 0); return Math.max(120, Math.min(420, 480 - fixed)); }
function loadWeight(t) { return t.load === 'high' ? 1.25 : t.load === 'medium' ? .8 : .45; }
function plannedLoad() { return plannedToday().reduce((s,t) => s + (t.estimate || 30) * loadWeight(t), 0); }
function tomorrowLessons() { const d = new Date(); d.setDate(d.getDate() + 1); return state.schedule.filter(x => x.active && x.day === d.getDay()).sort((a,b) => mins(a.start)-mins(b.start)); }

function pageHead(title, label = 'Study OS') { return `<header class="topline"><div><div class="eyebrow">${label}</div><h1 class="title">${title}</h1></div><div class="date">${dateLabel(today())}<br>${time()}</div></header>`; }
function nav() { const links = [['today','⌁',"Today's Plan"],['backlog','≡','Backlog'],['subjects','◌','Subjects'],['schedule','▦','Schedule'],['more','•••','More']]; return `<nav class="nav" aria-label="Main navigation">${links.map(([id,icon,name]) => `<button data-page="${id}" class="${state.page===id?'active':''}" aria-label="${name}"><b>${icon}</b><span>${name}</span></button>`).join('')}</nav>`; }
function taskCard(t, options = {}) { const isPlanned = t.plannedDate === today(); const timer = activeTimer(); const running = timer?.taskId === t.id; return `<article class="task load-${t.load || 'medium'}"><div class="row between"><div class="task-title">${esc(t.title)}</div><span class="pill ${t.load || 'medium'}">${t.load || 'medium'}</span></div><div class="task-meta">${subject(t.subjectId)} · ${formatMinutes(t.estimate)} est${t.actualTime ? ` · ${formatMinutes(t.actualTime)} actual` : ''}${t.dueDate ? ` · due ${t.dueDate}` : ''}${isPlanned && Number.isFinite(t.plannedStart) ? ` · ${clock(t.plannedStart)}` : ''}</div>${options.reason ? `<p class="muted" style="margin:7px 0 0">${esc(options.reason)}</p>` : ''}<div class="task-actions">${t.status !== 'COMPILED' ? `<button class="button small ${running ? 'primary':''}" data-action="timer" data-id="${t.id}">${running ? (timer.pausedAt ? 'Resume' : 'Pause') : 'Start timer'}</button>${running ? `<button class="button small" data-action="finish-timer" data-id="${t.id}">Finish timer</button>` : ''}<button class="button small" data-action="complete" data-id="${t.id}">Complete</button>` : ''}${!isPlanned && t.status !== 'COMPILED' ? `<button class="button small" data-action="schedule" data-id="${t.id}">Schedule</button>` : ''}<button class="button small ghost" data-action="split-task" data-id="${t.id}">Split</button><button class="button small ghost" data-action="edit-task" data-id="${t.id}">Edit</button>${options.debug ? `<button class="button small ghost" data-action="debug" data-id="${t.id}">Why did this fail?</button>` : ''}</div></article>`; }

function todayPage() {
  const planned = plannedToday(); const blocks = blocksForDay(state.schedule, today()); const currentCapacity = capacity(); const load = plannedLoad(); const pct = Math.min(100, Math.round(load / currentCapacity * 100)); const next = tomorrowLessons();
  return `${pageHead("Today's Plan", 'CONTROL PANEL')}<section class="card"><div class="section-head"><h2>Cognitive Battery</h2><span class="mono muted">${Math.max(0, currentCapacity-Math.round(load))}m remaining</span></div><div class="battery" aria-label="${pct}% of planning capacity used"><span style="width:${pct}%"></span></div><div class="row between muted"><span>${Math.round(load)}m planned load</span><span>${currentCapacity}m realistic capacity</span></div><p class="notice arabic">الخطة اقتراح، مش أوامر. اختاري اللي ينفع يومك.</p></section><section class="card"><div class="section-head"><h2>Fixed commitments</h2><button class="button small ghost" data-page="schedule">Edit</button></div>${blocks.length ? `<div class="timeline">${blocks.map(b => `<div class="time-row ${b.kind}"><span class="time">${clock(b.start)}–${clock(b.end)}</span>${esc(b.label)}</div>`).join('')}</div>` : `<div class="empty">No fixed commitments today. The planner can use a little more of the day.</div>`}</section><section class="card"><div class="section-head"><h2>Today’s tasks</h2><button class="button small primary" data-action="suggest">Suggest plan</button></div>${planned.length ? planned.map(t => taskCard(t)).join('') : `<div class="empty">No tasks chosen yet. Ask for a realistic suggestion, or pull one from Backlog.</div>`}</section><section class="card"><div class="section-head"><h2>RAM Dump</h2><span class="pill">fast capture</span></div><form data-form="ram" class="row"><input aria-label="Quick capture" name="title" placeholder="حل أسئلة الفصل الثالث" required /><button class="button primary">Save</button></form><p class="muted arabic">اكتبيها وسيبي التنظيم لبعدين.</p></section><section class="card"><div class="section-head"><h2>Tomorrow</h2><span class="muted">${dateLabel(isoDay(new Date(Date.now()+86400000)))}</span></div>${next.length ? `<div class="timeline">${next.map(x => `<div class="time-row ${x.physical?'commute':''}"><span class="time">${x.start}</span>${esc(x.subject)}${x.physical?' · 🚗 commute':''}</div>`).join('')}</div><p class="notice arabic">بكرة عندك ${next.map(x=>x.subject).join('، ')}.</p>` : `<div class="empty arabic">بكرة مفيش دروس ثابتة.</div>`}</section>`;
}
function backlogPage() { const open = state.tasks.filter(t => t.status !== 'COMPILED'); const overdue = open.filter(isOverdue); const soon = open.filter(t => !isOverdue(t) && t.dueDate && t.dueDate <= isoDay(new Date(Date.now()+3*86400000))); const rest = open.filter(t => !overdue.includes(t) && !soon.includes(t)); return `${pageHead('Backlog','QUEUE')}<section class="card"><p class="notice arabic">عندك ${open.length} حاجة وراكي، مش مطلوب تخلصي كله.</p><div class="row wrap"><button class="button small" data-action="open-task">+ New task</button><button class="button small" data-action="suggest">Suggest today</button></div></section>${queue('Overdue',overdue,true)}${queue('Due soon',soon,true)}${queue('Unscheduled & remaining',rest,true)}`; }
function queue(name, tasks, debug) { return `<section class="card"><div class="section-head"><h2>${name}</h2><span class="pill">${tasks.length}</span></div>${tasks.length ? tasks.map(t => taskCard(t,{debug})).join('') : `<div class="empty">Nothing here.</div>`}</section>`; }
function subjectsPage() { return `${pageHead('Subjects','ACTUAL PROGRESS')}<section class="card"><div class="section-head"><h2>Progress is completion, not pressure</h2><button class="button small" data-action="add-subject">+ Subject</button></div>${state.subjects.map(s => { const tasks = state.tasks.filter(t=>t.subjectId===s.id); const done = tasks.filter(t=>t.status==='COMPILED'); const pct = tasks.length ? Math.round(done.length/tasks.length*100) : 0; const overdue = tasks.filter(isOverdue).length; const study = state.sessions.filter(x=>x.subjectId===s.id).reduce((n,x)=>n+x.duration,0); return `<article class="task"><div class="row between"><div class="task-title">${esc(s.name)}</div><span class="mono" style="color:var(--green)">${pct}%</span></div><div class="battery"><span style="width:${pct}%"></span></div><div class="summary"><div class="metric"><b>${done.length}/${tasks.length}</b><span>completed</span></div><div class="metric"><b>${overdue}</b><span>overdue</span></div><div class="metric"><b>${formatMinutes(study)}</b><span>study time</span></div></div></article>`; }).join('') || `<div class="empty">No subjects yet.</div>`}</section>`; }
function schedulePage() { return `${pageHead('Schedule','FIXED COMMITMENTS')}<section class="card"><p class="notice arabic">المواصلات بتتحجز تلقائيًا قبل الدرس الحضوري.</p><button class="button primary" data-action="add-schedule">+ Add commitment</button></section>${days.map((name,day) => { const items=state.schedule.filter(x=>x.day===day).sort((a,b)=>mins(a.start)-mins(b.start)); return `<section class="card"><div class="section-head"><h2>${name}</h2><span class="pill">${items.length}</span></div>${items.length ? items.map(x=>`<div class="task"><div class="row between"><div class="task-title">${esc(x.subject)}</div><button class="button small ghost" data-action="edit-schedule" data-id="${x.id}">Edit</button></div><div class="task-meta">${x.start}${x.end?'–'+x.end:''} · ${x.physical ? `Physical · 🚗 ${x.commute}m commute` : 'Online · no commute'}${x.active?'':' · inactive'}</div></div>`).join('') : `<div class="empty">No fixed lessons.</div>`}</section>`; }).join('')}`; }
function morePage() { return `${pageHead('More','TOOLS')}<section class="card"><div class="tabs"><button class="button small ${state.more==='exams'?'active':''}" data-more="exams">Exams</button><button class="button small ${state.more==='history'?'active':''}" data-more="history">History</button><button class="button small ${state.more==='settings'?'active':''}" data-more="settings">Settings</button><button class="button small ${state.more==='backup'?'active':''}" data-more="backup">Backup</button></div>${state.more==='exams'?examPanel():state.more==='history'?historyPanel():state.more==='settings'?settingsPanel():backupPanel()}</section>`; }
function examPanel() {
  const ordered = [...state.exams].sort((a, b) => a.date.localeCompare(b.date));
  const list = ordered.length ? ordered.map(e => {
    const countdown = Math.ceil((new Date(`${e.date}T12:00:00`) - new Date()) / 86400000);
    const when = `${e.date}${e.time ? ` · ${e.time}` : ''} · ${countdown >= 0 ? `${countdown} days away` : 'passed'}`;
    return `<div class="task"><div class="row between"><div class="task-title">${subject(e.subjectId)}</div><button class="button small ghost" data-action="delete-exam" data-id="${e.id}">Remove</button></div><div class="task-meta">${when}</div>${e.notes ? `<p class="muted">${esc(e.notes)}</p>` : ''}</div>`;
  }).join('') : `<div class="empty arabic">مفيش امتحانات مسجلة. لما تضيفي واحد، المهام المتعلقة بالمادة هتاخد أولوية محسوبة.</div>`;
  return `<div class="section-head"><h2>Exams</h2><button class="button small primary" data-action="add-exam">+ Exam</button></div>${list}`;
}
function historyPanel() { const dates=[]; for(let i=55;i>=0;i--) dates.push(isoDay(new Date(Date.now()-i*86400000))); const max=Math.max(1,...dates.map(daySessions)); return `<div class="section-head"><h2>Study activity</h2><span class="muted">actual time</span></div><div class="heatmap">${dates.map(d=>{const v=daySessions(d), level=v===0?0:Math.ceil(v/max*4);const count=state.tasks.filter(t=>t.completedAt&&isoDay(new Date(t.completedAt))===d).length;return `<div class="heat l${level}" title="${d}: ${formatMinutes(v)}, ${count} completed" aria-label="${d}: ${formatMinutes(v)} study time, ${count} completed tasks"></div>`}).join('')}</div><div class="divider"></div>${dailyRecord(today())}`; }
function dailyRecord(date) { const rec=state.records.find(r=>r.date===date)||{}; const planned=state.tasks.filter(t=>t.plannedDate===date).length; const done=state.tasks.filter(t=>t.completedAt&&isoDay(new Date(t.completedAt))===date).length;return `<div class="section-head"><h2>Today’s log</h2><span class="pill">${date}</span></div><div class="summary"><div class="metric"><b>${planned}</b><span>planned tasks</span></div><div class="metric"><b>${done}</b><span>completed</span></div><div class="metric"><b>${formatMinutes(daySessions(date))}</b><span>actual study</span></div></div><div class="divider"></div><div class="row between"><div><b style="font-size:13px">Sleep context</b><div class="muted">${rec.sleep ? `${rec.sleep.start} → ${rec.sleep.wake} · ${rec.sleep.duration}h` : 'Not recorded'}</div></div><button class="button small" data-action="sleep">Record</button></div><div class="divider"></div><div class="row between"><div><b style="font-size:13px">Beyond Study</b><div class="muted arabic">${rec.beyond ? esc(rec.beyond) : 'Something I did for myself…'}</div></div><button class="button small" data-action="beyond">Add</button></div>`; }
function settingsPanel() { const s=state.settings; return `<div class="section-head"><h2>Settings</h2></div><div class="grid"><label class="field">Theme<select data-setting="theme"><option value="dark" ${s.theme==='dark'?'selected':''}>Dark control panel</option><option value="light" ${s.theme==='light'?'selected':''}>Light</option></select></label><label class="field">Default suggestion count<input data-setting="suggestionCount" type="number" min="1" max="8" value="${s.suggestionCount}" /></label><label class="field">Default commute minutes<input data-setting="defaultCommute" type="number" min="0" max="120" value="${s.defaultCommute}" /></label><label class="check"><input data-setting="notifyLessons" type="checkbox" ${s.notifications.lessons?'checked':''}/> Lesson and commute reminders (when browser supports them)</label><button class="button" data-action="notifications">Request notification permission</button><p class="muted">Notifications are optional and browser-dependent. This PWA never pretends background reminders are guaranteed.</p></div>`; }
function backupPanel() { return `<div class="section-head"><h2>Backup / Restore</h2></div><p class="muted">Your data lives in this browser’s IndexedDB. Keep an export before clearing browser data or changing devices.</p><div class="row wrap"><button class="button primary" data-action="export">Export JSON</button><label class="button">Import JSON<input id="backup-file" type="file" accept="application/json" class="hidden" /></label></div><div class="divider"></div><button class="button danger" data-action="reset-schedule">Reset seeded schedule</button><p class="muted">This only replaces the weekly schedule after confirmation. Tasks and history stay intact.</p>`; }

function renderModal() { if (!state.modal) return ''; const m=state.modal; let body='';
  if (m.kind==='task') body=taskForm(m.task);
  if (m.kind==='command') body=`<h2>Quick command</h2><p class="muted">Try <span class="mono">add physics medium 45m</span>. Ambiguous entries open the normal form.</p><form data-form="command" class="grid"><label class="field">Command<input name="command" autofocus placeholder="add chemistry high 45m" required /></label><div class="row"><button class="button primary">Parse task</button><button type="button" class="button" data-action="close">Cancel</button></div></form>`;
  if (m.kind==='debug') body=`<h2>Why did this fail?</h2><p class="muted">Optional signal for future planning — no judgment.</p><form data-form="debug" data-id="${m.id}" class="grid">${['Not enough time','Needs splitting','Low priority','Too difficult','Forgot','Unexpected interruption','Other'].map(x=>`<label class="check"><input name="reason" type="radio" value="${x}" required />${x}</label>`).join('')}<button class="button primary">Save note</button></form>`;
  if (m.kind==='schedule') body=scheduleForm(m.item);
  if (m.kind==='exam') body=examForm();
  if (m.kind==='sleep') body=`<h2>Sleep context</h2><p class="muted">Optional context only. No sleep score, no health claims.</p><form data-form="sleep" class="grid"><div class="grid two"><label class="field">Sleep start<input name="start" type="time" required /></label><label class="field">Wake time<input name="wake" type="time" required /></label></div><button class="button primary">Save context</button></form>`;
  if (m.kind==='beyond') body=`<h2>Beyond Study</h2><p class="muted arabic">اليوم مش بيتقاس بالمذاكرة بس.</p><form data-form="beyond" class="grid"><label class="field">One thing<select name="beyond"><option>اتحركت / مشيت</option><option>قرأت</option><option>رتبت حاجة</option><option>عملت حاجة بحبها</option><option>قضيت وقت مع أهلي</option><option>حاجة تانية</option></select></label><label class="field">Optional note<input name="note" placeholder="Something I did for myself..." /></label><button class="button primary">Save</button></form>`;
  if (m.kind==='suggest') { const result=suggestPlan({tasks:state.tasks,schedule:state.schedule,exams:state.exams,count:state.settings.suggestionCount}); body=`<h2>Suggested plan</h2><p class="muted">Built from available windows, deadlines, priorities, exams and cognitive load.</p>${result.suggestions.length?result.suggestions.map(t=>taskCard(t,{reason:t.reason})).join(''):`<div class="empty">No task fits a remaining window today. That is useful information, not a failure.</div>`}<div class="row" style="margin-top:12px"><button class="button primary" data-action="accept-suggestions">Accept suggestions</button><button class="button" data-action="close">Close</button></div>`; }
  return `<div class="modal-wrap" role="dialog" aria-modal="true"><section class="modal">${body}</section></div>`;
}
function taskForm(t={}) { return `<h2>${t.id?'Edit task':'New task'}</h2><form data-form="task" data-id="${t.id||''}" class="grid"><label class="field">Task title<input name="title" value="${esc(t.title||'')}" required autofocus placeholder="Solve chapter 3 questions" /></label><div class="grid two"><label class="field">Subject<select name="subjectId"><option value="">General</option>${state.subjects.map(s=>`<option value="${s.id}" ${t.subjectId===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label class="field">Due date<input name="dueDate" type="date" value="${t.dueDate||''}" /></label></div><div class="grid two"><label class="field">Priority<select name="priority">${['low','medium','high'].map(x=>`<option ${(t.priority||'medium')===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="field">Cognitive load<select name="load">${['low','medium','high'].map(x=>`<option ${(t.load||'medium')===x?'selected':''}>${x}</option>`).join('')}</select></label></div><label class="field">Estimated minutes<input name="estimate" type="number" min="5" step="5" value="${t.estimate||30}" required /></label><label class="check"><input type="checkbox" name="reminder" ${t.reminder?'checked':''} /> Reminder when supported</label><div class="row"><button class="button primary">${t.id?'Save changes':'Add to backlog'}</button><button type="button" class="button" data-action="close">Cancel</button>${t.id?`<button type="button" class="button danger" data-action="delete-task" data-id="${t.id}">Delete</button>`:''}</div></form>`; }
function scheduleForm(x={}) { return `<h2>${x.id?'Edit commitment':'Add commitment'}</h2><form data-form="schedule" data-id="${x.id||''}" class="grid"><label class="field">Subject / name<input name="subject" value="${esc(x.subject||'')}" required /></label><div class="grid two"><label class="field">Day<select name="day">${days.map((d,i)=>`<option value="${i}" ${x.day===i?'selected':''}>${d}</option>`).join('')}</select></label><label class="field">Start<input name="start" type="time" value="${x.start||'12:00'}" required /></label></div><div class="grid two"><label class="field">End (optional)<input name="end" type="time" value="${x.end||''}" /></label><label class="field">Commute before (min)<input name="commute" type="number" min="0" value="${x.commute??state.settings.defaultCommute}" /></label></div><label class="check"><input name="physical" type="checkbox" ${x.physical?'checked':''}/> Physical lesson (blocks commute before it)</label><label class="check"><input name="active" type="checkbox" ${x.active!==false?'checked':''}/> Active</label><div class="row"><button class="button primary">Save commitment</button><button class="button" type="button" data-action="close">Cancel</button>${x.id?`<button class="button danger" type="button" data-action="delete-schedule" data-id="${x.id}">Delete</button>`:''}</div></form>`; }
function examForm() { return `<h2>Add exam</h2><form data-form="exam" class="grid"><label class="field">Subject<select name="subjectId" required>${state.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><div class="grid two"><label class="field">Date<input name="date" type="date" required /></label><label class="field">Time (optional)<input name="time" type="time" /></label></div><label class="field">Notes<textarea name="notes" placeholder="Scope, location, anything useful"></textarea></label><button class="button primary">Save exam</button></form>`; }

function render() { const page = state.page==='today'?todayPage():state.page==='backlog'?backlogPage():state.page==='subjects'?subjectsPage():state.page==='schedule'?schedulePage():morePage(); app.innerHTML=`<div class="shell">${page}</div><button class="fab" data-action="command" aria-label="Quick command">+</button>${nav()}${renderModal()}${state.toast?`<div class="toast">${esc(state.toast)}</div>`:''}`; }

document.addEventListener('click', async event => { const target=event.target.closest('[data-action],[data-page],[data-more]'); if(!target)return; const {action,page,more,id}=target.dataset;
  if(page){state.page=page;render();return} if(more){state.more=more;render();return}
  if(action==='close'){state.modal=null;render();return} if(action==='command'){state.modal={kind:'command'};render();return} if(action==='open-task'){state.modal={kind:'task'};render();return}
  if(action==='edit-task'){state.modal={kind:'task',task:taskFor(id)};render();return} if(action==='add-subject'){const name=prompt('Subject name');if(name?.trim()){state.subjects.push({id:uid('subject'),name:name.trim(),createdAt:Date.now()});await saveCollection('subjects');render()}return}
  if(action==='add-schedule'){state.modal={kind:'schedule'};render();return} if(action==='edit-schedule'){state.modal={kind:'schedule',item:state.schedule.find(x=>x.id===id)};render();return} if(action==='add-exam'){state.modal={kind:'exam'};render();return}
  if(action==='debug'){state.modal={kind:'debug',id};render();return} if(action==='sleep'||action==='beyond'){state.modal={kind:action};render();return}
  if(action==='suggest'){state.modal={kind:'suggest'};render();return} if(action==='accept-suggestions'){const s=suggestPlan({tasks:state.tasks,schedule:state.schedule,exams:state.exams,count:state.settings.suggestionCount}).suggestions;for(const x of s)await persistTask({...x,reason:undefined});state.modal=null;toast(`${s.length} task${s.length===1?'':'s'} added to today.`);return}
  if(action==='schedule'){const t=taskFor(id);await persistTask({...t,plannedDate:today(),plannedStart:findPlanStart(t)});toast('Scheduled for today.');return}
  if(action==='split-task'){const t=taskFor(id);const first=Math.max(10,Math.ceil((t.estimate||30)/2));const second=Math.max(10,(t.estimate||30)-first);await persistTask({...t,estimate:first});await persistTask({...t,id:uid('task'),title:`${t.title} — part 2`,estimate:second,plannedDate:null,plannedStart:null,status:'PENDING',createdAt:Date.now()});toast('Split into two smaller backlog tasks.');return}
  if(action==='complete'){await completeTask(id);return} if(action==='timer'){await timer(id);return} if(action==='finish-timer'){await stopTimer(false);render();return}
  if(action==='delete-task'){if(confirm('Delete this task? This cannot be undone unless it is in a backup.')){state.tasks=state.tasks.filter(x=>x.id!==id);await saveCollection('tasks');state.modal=null;render()}return}
  if(action==='delete-schedule'){if(confirm('Delete this fixed commitment?')){state.schedule=state.schedule.filter(x=>x.id!==id);await saveCollection('schedule');state.modal=null;render()}return}
  if(action==='delete-exam'){state.exams=state.exams.filter(x=>x.id!==id);await saveCollection('exams');render();return}
  if(action==='export'){downloadBackup(await exportBackup());toast('Backup downloaded.');return} if(action==='reset-schedule'){if(confirm('Replace your current weekly schedule with the initial editable schedule?')){state.schedule=initialSchedule();await saveCollection('schedule');toast('Seed schedule restored.')}return}
  if(action==='notifications'){if(!('Notification'in window)){toast('This browser does not support notifications.');return}const p=await Notification.requestPermission();if(p==='granted'){state.settings.notifications.lessons=true;await saveSettings();toast('Permission granted. Keep the app open for best reliability.')}else toast('Notification permission was not granted.');return}
});
function findPlanStart(t) { const blocks=blocksForDay(state.schedule,today()); const planned=plannedToday(); const capacityWindows = suggestPlan({tasks:[...state.tasks.filter(x=>x.id!==t.id),t],schedule:state.schedule,exams:state.exams,count:1}).windows; return capacityWindows.find(w=>w.end-w.start>=(t.estimate||30))?.start ?? 20*60; }
async function completeTask(id) { const t=taskFor(id); const timer=activeTimer(); if(timer?.taskId===id) await stopTimer(true); await persistTask({...t,status:'COMPILED',completedAt:Date.now()}); toast(`Compiled. Finishing this reduced your active backlog.`); }
async function timer(id) { const timer=activeTimer(); if(timer?.taskId===id){ if(timer.pausedAt){timer.startedAt=Date.now();timer.pausedAt=null;}else{timer.elapsed+=(Date.now()-timer.startedAt)/60000;timer.pausedAt=Date.now();}state.settings.timer=timer;await saveSettings();render();return} if(timer) await stopTimer(false); const task=taskFor(id); await persistTask({...task,status:'EXECUTING'}); state.settings.timer={taskId:id,startedAt:Date.now(),elapsed:0,pausedAt:null};await saveSettings();render(); }
async function stopTimer(complete=false) { const timer=activeTimer();if(!timer)return;const duration=Math.max(1,Math.round(timer.elapsed+(timer.pausedAt?0:(Date.now()-timer.startedAt)/60000)));const task=taskFor(timer.taskId);state.sessions.push({id:uid('session'),taskId:task.id,subjectId:task.subjectId,date:today(),duration,createdAt:Date.now()});await persistTask({...task,actualTime:(task.actualTime||0)+duration,status:complete?'EXECUTING':'PENDING'});state.settings.timer=null;await saveCollection('sessions');await saveSettings(); if(!complete)toast(`${duration} minutes saved.`); }

document.addEventListener('submit', async event => { const form=event.target; if(!form.dataset.form)return;event.preventDefault(); const d=new FormData(form), name=form.dataset.form;
  if(name==='ram'){await persistTask({id:uid('task'),title:d.get('title').trim(),subjectId:'',priority:'medium',estimate:30,load:'medium',status:'PENDING',createdAt:Date.now(),ramDump:true});form.reset();toast('Saved to Backlog.');return}
  if(name==='task'){const existing=taskFor(form.dataset.id)||{};await persistTask({...existing,id:existing.id||uid('task'),title:d.get('title').trim(),subjectId:d.get('subjectId'),dueDate:d.get('dueDate'),priority:d.get('priority'),load:d.get('load'),estimate:Number(d.get('estimate')),reminder:d.get('reminder')==='on',status:existing.status||'PENDING',createdAt:existing.createdAt||Date.now()});state.modal=null;toast(existing.id?'Task updated.':'Added to backlog.');return}
  if(name==='schedule'){const existing=state.schedule.find(x=>x.id===form.dataset.id)||{};const physical=d.get('physical')==='on';const item={...existing,id:existing.id||uid('schedule'),day:Number(d.get('day')),subject:d.get('subject').trim(),start:d.get('start'),end:d.get('end')||null,physical,commute:physical?Number(d.get('commute')):0,active:d.get('active')==='on',createdAt:existing.createdAt||Date.now()};const i=state.schedule.findIndex(x=>x.id===item.id);if(i<0)state.schedule.push(item);else state.schedule[i]=item;await saveCollection('schedule');state.modal=null;toast('Schedule updated.');return}
  if(name==='exam'){state.exams.push({id:uid('exam'),subjectId:d.get('subjectId'),date:d.get('date'),time:d.get('time'),notes:d.get('notes'),createdAt:Date.now()});await saveCollection('exams');state.modal=null;toast('Exam saved.');return}
  if(name==='debug'){const t=taskFor(form.dataset.id);await persistTask({...t,debugReason:d.get('reason'),debuggedAt:Date.now()});state.modal=null;toast('Saved as a planning signal.');return}
  if(name==='sleep'){await saveRecord({sleep:{start:d.get('start'),wake:d.get('wake'),duration:sleepHours(d.get('start'),d.get('wake'))}});state.modal=null;toast('Sleep context saved.');return}
  if(name==='beyond'){await saveRecord({beyond:[d.get('beyond'),d.get('note')].filter(Boolean).join(' — ')});state.modal=null;toast('Saved.');return}
  if(name==='command'){const text=d.get('command').trim();const parsed=parseCommand(text);if(!parsed.title){toast('Try “add chemistry high 45m”, or use the normal task form.');return}state.modal={kind:'task',task:parsed};render();return}
});
function parseCommand(text) { const tokens=text.toLowerCase().replace(/^add\s+/,'').split(/\s+/); let estimate=30,load='medium',priority='medium',subjectId=''; const min=tokens.find(x=>/^\d+m?$/.test(x));if(min){estimate=Number(min.replace('m',''));tokens.splice(tokens.indexOf(min),1)} for(const x of ['low','medium','high'])if(tokens.includes(x)){load=x;tokens.splice(tokens.indexOf(x),1);break} const found=state.subjects.find(s=>tokens.includes(s.name.toLowerCase()));if(found){subjectId=found.id;tokens.splice(tokens.indexOf(found.name.toLowerCase()),1)} return {title:tokens.join(' ').trim(),estimate,load,priority,subjectId}; }
function sleepHours(start,wake){let a=mins(start),b=mins(wake);if(b<a)b+=1440;return Math.round((b-a)/6)/10;}
async function saveRecord(patch){const i=state.records.findIndex(x=>x.date===today());const next={...(i>=0?state.records[i]:{id:uid('record'),date:today(),createdAt:Date.now()}),...patch,updatedAt:Date.now()};if(i>=0)state.records[i]=next;else state.records.push(next);await saveCollection('records');}
document.addEventListener('change', async event => { const input=event.target;if(input.id==='backup-file'&&input.files[0]){try{const data=JSON.parse(await input.files[0].text());if(!confirm(`Restore backup from ${data.exportedAt||'unknown date'}? This replaces current local data. Export first if you need to keep it.`))return;await restoreBackup(data);location.reload()}catch(e){toast(e.message||'Could not read that backup.')}}if(input.dataset.setting){const key=input.dataset.setting;if(key==='notifyLessons')state.settings.notifications.lessons=input.checked;else state.settings[key]=input.type==='number'?Number(input.value):input.value;document.documentElement.dataset.theme=state.settings.theme;await saveSettings();render();}});
const notified = new Set();
function notificationCheck() { if (!state.settings?.notifications?.lessons || Notification.permission !== 'granted') return; const now = new Date(); const nowMinutes = now.getHours() * 60 + now.getMinutes(); for (const item of state.schedule.filter(x => x.active && x.day === now.getDay())) { const target = mins(item.start) - (item.physical ? item.commute : 10); const key = `${today()}-${item.id}-${target}`; if (nowMinutes >= target && nowMinutes < target + 2 && !notified.has(key)) { notified.add(key); new Notification(item.physical ? `انزلي دلوقتي — عندك ${item.subject} الساعة ${item.start}.` : `درس ${item.subject} هيبدأ الساعة ${item.start}.`); } } }
setInterval(()=>{if(activeTimer()&&!activeTimer().pausedAt)render(); notificationCheck()},15000);
init().catch(error=>{console.error(error);app.innerHTML=`<div class="shell"><section class="card"><h1>Study OS could not start</h1><p class="muted">${esc(error.message)}. Please reload; your existing browser data has not been erased.</p></section></div>`});
